find_path(PROJ_INCLUDE_DIR NAMES proj_api.h
	PATHS ${CONAN_INCLUDE_DIRS_PROJ}
	NO_DEFAULT_PATH)

find_library(PROJ_LIBRARY NAMES ${CONAN_LIBS_PROJ}
	PATHS ${CONAN_LIB_DIRS_PROJ}
	NO_DEFAULT_PATH)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PROJ
	REQUIRED_VARS PROJ_LIBRARY PROJ_INCLUDE_DIR
	FOUND_VAR PROJ_FOUND
)

set(PROJ_INCLUDE_DIRS ${PROJ_INCLUDE_DIR})
set(PROJ_LIBRARIES ${PROJ_LIBRARY})

mark_as_advanced(PROJ_INCLUDE_DIR PROJ_LIBRARY)
